/**
 * Home page component
 * Displays introduction to Fractalite and fractal mathematics
 */

import "./Home.css";
import ApollonianGasketWhite from "../assets/ApollonianGasketWhite.png";
import HomeCollageFractalite from "../assets/Home_Collage_Fractalite.png";
import HistoryOfFractals from "../assets/HistoryofFractals.png";

/**
 * Home component that renders the landing page
 * @returns {JSX.Element} The home page with fractal information
 */
export default function Home() {
    return (
        <div className="Home-container-div">
            <div
                className="Home-image-block"
                id="Home-fractalite-image-collage"
            >
                <img 
                    src={HomeCollageFractalite} 
                    width={"80%"} 
                    alt="Fractalite collage showcasing various fractal patterns"
                />
            </div>
            <div className="Home-text-block" id="home-text1">
                <h2>What's Fractalite?</h2>
                <p>
                    <span id="span-1">Fractalite</span> is a digital canvas
                    built with the power of WebGL to render breathtakingly
                    intricate fractal art. This interactive explorer unveils the
                    captivating beauty of self-similar yet endlessly
                    non-repeating patterns, bringing these mathematical wonders
                    to life on your screen. Conceived as an educational tool,
                    Fractalite aims to illuminate the fascinating principles
                    behind these complex structures. More than just a generator,
                    this is my love-letter to these stunning visuals, intricate
                    patterns, & unmatched natural beauty inviting you to
                    discover the inherent artistry within mathematical
                    equations.
                </p>
            </div>
            <div className="Home-text-block" id="home-text2">
                <h2>What exactly is a Fractal?</h2>
                <p>
                    Fractals are complex geometric figures that often display
                    intricate patterns repeating at different scales, a property
                    known as self-similarity. However, a common misconception is
                    that all fractals are self-similar—while many well-known
                    examples like the Mandelbrot set or Sierpiński triangle do
                    exhibit this trait, self-similarity is not a strict
                    requirement for a shape to be classified as a fractal.
                    Instead, what defines a fractal is typically its fine
                    structure at arbitrarily small scales, its recursive or
                    iterative generation process, and its often non-integer
                    (fractal) dimension. Another misconception is that fractals
                    are purely chaotic or random, when in fact they are often
                    generated by deterministic mathematical rules. Some also
                    believe fractals are limited to computer graphics or
                    abstract art, but they naturally occur in a wide variety of
                    physical systems—like snowflakes, mountain ranges, and even
                    blood vessels.
                </p>
            </div>
            <div
                className="Home-image-block"
                id="Home-fractalite-image-collage"
            >
                <img 
                    src={ApollonianGasketWhite} 
                    width={"80%"} 
                    alt="Apollonian Gasket fractal pattern"
                />
            </div>
            <div
                className="Home-image-block"
                id="Home-fractalite-image-collage"
            >
                <img 
                    src={HistoryOfFractals} 
                    width={"80%"} 
                    alt="Historical timeline of fractal mathematics"
                />
            </div>
            <div className="Home-text-block" id="home-text3">
                <h2>The History of Fractals</h2>
                <p>
                    The idea of fractals dates back several centuries, even
                    though the term itself was only introduced in the 20th
                    century. As early as the 17th century, mathematicians like
                    Gottfried Wilhelm Leibniz and Isaac Newton explored concepts
                    involving infinite series and curves that didn't fit neatly
                    into classical geometry.
                </p>
                <p>
                    In the 19th century, mathematicians such as Karl
                    Weierstrass, Giuseppe Peano, and Georg Cantor began
                    developing strange mathematical objects like:
                </p>
                <ul className="home-ul">
                    <li>
                        The Weierstrass function - continuous everywhere but
                        differentiable nowhere.
                    </li>
                    <li>
                        The Peano curve - a space-filling curve that completely
                        covers a square.
                    </li>
                    <li>
                        The Cantor set - a seemingly simple yet infinitely
                        fragmented set.
                    </li>
                </ul>
                <p>
                    These early examples were seen as mathematical oddities or
                    "pathological" cases at the time.
                </p>
            </div>
        </div>
    );
}
